// sme_oprosnyk/frontend/src/steps/StepSummary.tsx
import { FileText, AlertCircle } from 'lucide-react'
import { Lang, SphereData, ClientInfo } from '../types'
import { t } from '../i18n'
import Card from '../components/Card'
import Button from '../components/Button'

interface Props {
  lang: Lang
  pinflInn: string
  clientInfo: ClientInfo | null
  sphereCount: number
  spheres: SphereData[]
  onBack: () => void
  onSubmit: () => void
  submitting: boolean
  submitError: string | null
}

function Row({ label, value }: { label: string; value: string | number | undefined }) {
  if (!value && value !== 0) return null
  return (
    <div className="py-2.5 grid grid-cols-2 gap-4 border-b border-border last:border-0">
      <p className="text-xs text-muted font-medium leading-relaxed">{label}</p>
      <p className="text-sm text-gray-900 font-semibold break-words">{String(value)}</p>
    </div>
  )
}

export default function StepSummary({
  lang, pinflInn, clientInfo: ci, sphereCount, spheres, onBack, onSubmit, submitting, submitError
}: Props) {
  const ru = lang === 'ru'

  return (
    <div className="space-y-6">
      <div className="text-center space-y-2">
        <div className="inline-flex items-center justify-center w-14 h-14 bg-blue-50 rounded-2xl">
          <FileText size={28} className="text-accent" />
        </div>
        <h2 className="text-2xl font-bold text-primary">{t(lang, 'summary_title')}</h2>
        <p className="text-sm text-muted">{t(lang, 'summary_subtitle')}</p>
      </div>

      {/* General info from Руйхат-2 */}
      <Card padding="md">
        <p className="text-xs font-bold text-accent uppercase tracking-wide mb-3">
          {ru ? 'Общая информация' : 'Umumiy ma\'lumot'}
        </p>
        <Row label={ru ? 'ПИНФЛ / ИНН' : 'PINFL / INN'} value={pinflInn} />
        {ci && <>
          <Row label={ru ? 'Наименование организации' : 'Tashkilot nomi'} value={ci.company_name} />
          <Row label={ru ? 'Директор' : 'Direktor'} value={ci.director} />
          <Row label={ru ? 'Главный бухгалтер' : 'Bosh buxgalter'} value={ci.accountant} />
          <Row label={ru ? 'Юридический адрес' : 'Yuridik manzil'} value={ci.reg_address} />
          <Row label={ru ? 'Телефон' : 'Telefon'} value={ci.phone} />
          <Row label={ru ? 'Вид деятельности' : 'Faoliyat turi'} value={ci.activity_type} />
        </>}
        <Row label={ru ? 'Количество сфер' : 'Soha soni'} value={sphereCount} />
      </Card>

      {/* Financial indicators — always shown when clientInfo exists */}
      {ci && (
        <Card padding="md">
          <p className="text-xs font-bold text-accent uppercase tracking-wide mb-3">
            {ru ? 'Финансовые показатели' : 'Moliyaviy ko\'rsatkichlar'}
          </p>
          <Row label={ru ? 'Общий оборот (сум)' : 'Jami aylanma (so\'m)'} value={ci.turnover_all || '—'} />
          <Row label={ru ? 'Дебет (сум)' : 'Debet (so\'m)'} value={ci.turnover_debit || '—'} />
          <Row label={ru ? 'Кредит (сум)' : 'Kredit (so\'m)'} value={ci.turnover_credit || '—'} />
          <Row label={ru ? 'Фонд оплаты труда' : 'Ish haqi jamg\'armasi'} value={ci.sal_sum || '—'} />
          <Row label={ru ? 'Кол-во акционеров' : 'Aksiyadorlar soni'} value={ci.shareholders_count || '—'} />
        </Card>
      )}

      {/* Sphere answers */}
      {spheres.map((sphere, si) => (
        <Card key={si} padding="md">
          <div className="flex items-center gap-3 mb-3">
            <span className="text-xs font-bold text-white bg-accent px-3 py-1 rounded-full">
              {ru ? 'Сфера' : 'Soha'} {sphere.sphere_number}
            </span>
            <span className="text-sm font-semibold text-gray-800">
              {ru ? sphere.category_name_ru : sphere.category_name_uz}
            </span>
          </div>
          <div className="divide-y divide-border">
            {sphere.answers.map(ans => (
              <div key={ans.question_id} className="py-2.5 grid grid-cols-2 gap-4">
                <p className="text-xs text-muted font-medium">{ru ? ans.question_text_ru : ans.question_text_uz}</p>
                <p className="text-sm text-gray-900 font-semibold break-words">
                  {ans.answer || <span className="text-gray-300 italic">—</span>}
                </p>
              </div>
            ))}
          </div>
        </Card>
      ))}

      {submitError && (
        <div className="flex items-start gap-3 bg-red-50 border border-red-200 rounded-card p-4">
          <AlertCircle size={18} className="text-error mt-0.5 shrink-0" />
          <p className="text-sm text-error">{submitError}</p>
        </div>
      )}

      <div className="flex gap-3">
        <Button variant="secondary" onClick={onBack} className="flex-1" disabled={submitting}>
          {t(lang, 'back')}
        </Button>
        <Button variant="primary" onClick={onSubmit} className="flex-1" disabled={submitting}>
          {submitting ? t(lang, 'submitting') : t(lang, 'submit')}
        </Button>
      </div>
    </div>
  )
}

// frontend/src/components/smeProfile/StepSummary.vue
<script setup>
import { useI18n } from 'vue-i18n'
import AppIcon from '@/components/AppIcon.vue'

defineProps({
  pinflInn: { type: String, required: true },
  clientInfo: { type: Object, default: null },
  sphereCount: { type: Number, required: true },
  spheres: { type: Array, required: true },
  submitting: { type: Boolean, default: false },
  submitError: { type: String, default: '' },
})
const emit = defineEmits(['back', 'submit'])

const { t, locale } = useI18n()

function show(v) {
  return v && String(v).trim() !== ''
}
</script>

<template>
  <div class="space-y-6">
    <div class="text-center space-y-2">
      <div class="inline-flex items-center justify-center w-14 h-14 bg-primary/10 rounded-2xl">
        <AppIcon name="fact_check" class="text-primary text-2xl" />
      </div>
      <h2 class="text-2xl font-bold text-on-surface">{{ t('smeProfile.summary.title') }}</h2>
      <p class="text-sm text-on-surface-variant">{{ t('smeProfile.summary.subtitle') }}</p>
    </div>

    <div class="bg-surface-container-lowest rounded-card p-5 shadow-sm">
      <p class="text-xs font-bold text-primary uppercase tracking-wide mb-3">
        {{ t('smeProfile.summary.general') }}
      </p>
      <div class="divide-y divide-outline-variant">
        <div class="py-2.5 grid grid-cols-2 gap-4">
          <p class="text-xs text-on-surface-variant font-medium">{{ t('smeProfile.fields.pinflInn') }}</p>
          <p class="text-sm font-semibold text-on-surface break-words">{{ pinflInn }}</p>
        </div>
        <template v-if="clientInfo">
          <div v-if="show(clientInfo.company_name)" class="py-2.5 grid grid-cols-2 gap-4">
            <p class="text-xs text-on-surface-variant font-medium">{{ t('smeProfile.fields.companyFull') }}</p>
            <p class="text-sm font-semibold text-on-surface break-words">{{ clientInfo.company_name }}</p>
          </div>
          <div v-if="show(clientInfo.director)" class="py-2.5 grid grid-cols-2 gap-4">
            <p class="text-xs text-on-surface-variant font-medium">{{ t('smeProfile.fields.director') }}</p>
            <p class="text-sm font-semibold text-on-surface break-words">{{ clientInfo.director }}</p>
          </div>
          <div v-if="show(clientInfo.accountant)" class="py-2.5 grid grid-cols-2 gap-4">
            <p class="text-xs text-on-surface-variant font-medium">{{ t('smeProfile.fields.accountant') }}</p>
            <p class="text-sm font-semibold text-on-surface break-words">{{ clientInfo.accountant }}</p>
          </div>
          <div v-if="show(clientInfo.reg_address)" class="py-2.5 grid grid-cols-2 gap-4">
            <p class="text-xs text-on-surface-variant font-medium">{{ t('smeProfile.fields.regAddress') }}</p>
            <p class="text-sm font-semibold text-on-surface break-words">{{ clientInfo.reg_address }}</p>
          </div>
          <div v-if="show(clientInfo.phone)" class="py-2.5 grid grid-cols-2 gap-4">
            <p class="text-xs text-on-surface-variant font-medium">{{ t('smeProfile.fields.phone') }}</p>
            <p class="text-sm font-semibold text-on-surface break-words">{{ clientInfo.phone }}</p>
          </div>
          <div v-if="show(clientInfo.activity_type)" class="py-2.5 grid grid-cols-2 gap-4">
            <p class="text-xs text-on-surface-variant font-medium">{{ t('smeProfile.fields.activityType') }}</p>
            <p class="text-sm font-semibold text-on-surface break-words">{{ clientInfo.activity_type }}</p>
          </div>
        </template>
        <div class="py-2.5 grid grid-cols-2 gap-4">
          <p class="text-xs text-on-surface-variant font-medium">{{ t('smeProfile.fields.sphereCount') }}</p>
          <p class="text-sm font-semibold text-on-surface">{{ sphereCount }}</p>
        </div>
      </div>
    </div>

    <div v-if="clientInfo" class="bg-surface-container-lowest rounded-card p-5 shadow-sm">
      <p class="text-xs font-bold text-primary uppercase tracking-wide mb-3">
        {{ t('smeProfile.summary.financials') }}
      </p>
      <div class="divide-y divide-outline-variant">
        <div class="py-2.5 grid grid-cols-2 gap-4">
          <p class="text-xs text-on-surface-variant font-medium">{{ t('smeProfile.fields.turnoverAll') }}</p>
          <p class="text-sm font-semibold text-on-surface">{{ clientInfo.turnover_all || '—' }}</p>
        </div>
        <div class="py-2.5 grid grid-cols-2 gap-4">
          <p class="text-xs text-on-surface-variant font-medium">{{ t('smeProfile.fields.debit') }}</p>
          <p class="text-sm font-semibold text-on-surface">{{ clientInfo.turnover_debit || '—' }}</p>
        </div>
        <div class="py-2.5 grid grid-cols-2 gap-4">
          <p class="text-xs text-on-surface-variant font-medium">{{ t('smeProfile.fields.credit') }}</p>
          <p class="text-sm font-semibold text-on-surface">{{ clientInfo.turnover_credit || '—' }}</p>
        </div>
        <div class="py-2.5 grid grid-cols-2 gap-4">
          <p class="text-xs text-on-surface-variant font-medium">{{ t('smeProfile.fields.salSum') }}</p>
          <p class="text-sm font-semibold text-on-surface">{{ clientInfo.sal_sum || '—' }}</p>
        </div>
        <div class="py-2.5 grid grid-cols-2 gap-4">
          <p class="text-xs text-on-surface-variant font-medium">{{ t('smeProfile.fields.shareholders') }}</p>
          <p class="text-sm font-semibold text-on-surface">{{ clientInfo.shareholders_count || '—' }}</p>
        </div>
      </div>
    </div>

    <div v-for="(sphere, si) in spheres" :key="si" class="bg-surface-container-lowest rounded-card p-5 shadow-sm">
      <div class="flex items-center gap-3 mb-3">
        <span class="text-xs font-bold text-white bg-primary px-3 py-1 rounded-full">
          {{ t('smeProfile.fields.sphere') }} {{ sphere.sphere_number }}
        </span>
        <span class="text-sm font-semibold text-on-surface">
          {{ locale === 'ru' ? sphere.category_name_ru : sphere.category_name_uz }}
        </span>
      </div>
      <div class="divide-y divide-outline-variant">
        <div v-for="ans in sphere.answers" :key="ans.question_id" class="py-2.5 grid grid-cols-2 gap-4">
          <p class="text-xs text-on-surface-variant font-medium">
            {{ locale === 'ru' ? ans.question_text_ru : ans.question_text_uz }}
          </p>
          <p class="text-sm font-semibold text-on-surface break-words">
            {{ ans.answer || '—' }}
          </p>
        </div>
      </div>
    </div>

    <div
      v-if="submitError"
      class="flex items-start gap-3 bg-red-50 border border-red-200 rounded-card p-4"
    >
      <AppIcon name="error" class="text-error mt-0.5 shrink-0" />
      <p class="text-sm text-error">{{ submitError }}</p>
    </div>

    <div class="flex gap-3">
      <button
        class="inline-flex items-center justify-center gap-2 flex-1 px-5 py-3 bg-surface-container text-on-surface border border-outline-variant rounded-btn text-sm font-semibold hover:bg-surface-container-high transition-all disabled:opacity-50 disabled:cursor-not-allowed"
        :disabled="submitting"
        @click="emit('back')"
      >
        <AppIcon name="arrow_back" />
        {{ t('smeProfile.back') }}
      </button>
      <button
        class="inline-flex items-center justify-center gap-2 flex-1 px-5 py-3 bg-primary text-white rounded-btn text-sm font-semibold hover:bg-primary/90 active:scale-[0.99] transition-all shadow-sm disabled:opacity-50 disabled:cursor-not-allowed"
        :disabled="submitting"
        @click="emit('submit')"
      >
        <AppIcon v-if="!submitting" name="check_circle" />
        <span
          v-else
          class="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin"
        />
        {{ submitting ? t('smeProfile.submitting') : t('smeProfile.submit') }}
      </button>
    </div>
  </div>
</template>
