// sme_oprosnyk/frontend/src/steps/StepPinfl.tsx
import { useState } from 'react'
import { UserCheck, Search, Building2, User, Phone, MapPin, AlertCircle } from 'lucide-react'
import { Lang, ClientInfo } from '../types'
import { t } from '../i18n'
import { lookupClient } from '../api'
import Card from '../components/Card'
import Button from '../components/Button'

interface Props {
  lang: Lang
  initialValue: string
  initialClientInfo: ClientInfo | null
  initialSphereCount: number
  onNext: (val: string, clientInfo: ClientInfo | null, sphereCount: number) => void
}

export default function StepPinfl({ lang, initialValue, initialClientInfo, initialSphereCount, onNext }: Props) {
  const [value, setValue]           = useState(initialValue)
  const [error, setError]           = useState('')
  const [searching, setSearching]   = useState(false)
  const [clientInfo, setClientInfo] = useState<ClientInfo | null>(initialClientInfo)
  const [notFound, setNotFound]     = useState(false)
  const [sphereCount, setSphereCount] = useState(initialSphereCount)
  const [searched, setSearched] = useState(!!initialClientInfo)

  const ru = lang === 'ru'

  const handleSearch = async () => {
    if (!value.trim()) { setError(t(lang, 'error_empty')); return }
    setSearching(true); setError(''); setNotFound(false); setClientInfo(null); setSearched(false)
    try {
      const res = await lookupClient(value.trim())
      if (res.found) {
        setClientInfo({
          company_name:      res.company_name,
          director:          res.director,
          reg_address:       res.reg_address,
          phone:             res.phone,
          turnover_debit:    res.turnover_debit,
          turnover_credit:   res.turnover_credit,
          turnover_all:      res.turnover_all,
          shareholders_count: res.shareholders_count,
          accountant:        res.accountant,
          activity_type:     res.activity_type,
          sal_sum:           res.sal_sum,
        })
      } else {
        setNotFound(true)
        setSearched(true)
      }
    } catch {
      setError(t(lang, 'error_backend'))
    } finally {
      setSearching(false)
      setSearched(true)
    }
  }

  const handleNext = () => {
    if (!value.trim()) { setError(t(lang, 'error_empty')); return }
    onNext(value.trim(), clientInfo, sphereCount)
  }

  const infoRows: Array<{ icon: React.ReactNode; label: string; val: string }> = clientInfo
    ? [
        { icon: <Building2 size={15} className="text-accent" />, label: ru ? 'Организация' : 'Tashkilot',  val: clientInfo.company_name },
        { icon: <User      size={15} className="text-accent" />, label: ru ? 'Директор'    : 'Direktor',   val: clientInfo.director },
        { icon: <MapPin    size={15} className="text-accent" />, label: ru ? 'Адрес'       : 'Manzil',     val: clientInfo.reg_address },
        { icon: <Phone     size={15} className="text-accent" />, label: ru ? 'Телефон'     : 'Telefon',    val: clientInfo.phone },
      ].filter(r => r.val)
    : []

  return (
    <div className="space-y-6">
      <div className="text-center space-y-3">
        <div className="inline-flex items-center justify-center w-16 h-16 bg-blue-50 rounded-2xl">
          <UserCheck size={32} className="text-accent" />
        </div>
        <div>
          <h2 className="text-2xl font-bold text-primary">{t(lang, 'pinfl_title')}</h2>
          <p className="text-sm text-muted mt-1">{t(lang, 'pinfl_hint')}</p>
        </div>
      </div>

      <Card>
        <div className="space-y-4">
          <label className="block text-sm font-semibold text-gray-700">{t(lang, 'pinfl_label')}</label>

          <div className="flex gap-2">
            <input
              type="text"
              value={value}
              onChange={e => { setValue(e.target.value); setError(''); setClientInfo(null); setNotFound(false) }}
              onKeyDown={e => e.key === 'Enter' && handleSearch()}
              placeholder={t(lang, 'pinfl_placeholder')}
              className={`flex-1 px-4 py-3.5 border rounded-input text-sm focus:outline-none focus:ring-2 focus:ring-accent/30 focus:border-accent transition-colors ${error ? 'border-error bg-red-50' : 'border-border'}`}
              autoFocus
            />
            <button
              onClick={handleSearch}
              disabled={searching || !value.trim()}
              className="px-4 py-3.5 bg-accent text-white rounded-input text-sm font-semibold hover:bg-blue-600 active:scale-95 transition-all disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2 shrink-0"
            >
              {searching
                ? <span className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
                : <Search size={16} />}
              {ru ? 'Поиск' : 'Qidirish'}
            </button>
          </div>

          {error && <p className="text-xs text-error font-medium">{error}</p>}

          {notFound && !clientInfo && (
            <div className="flex items-center gap-2 bg-amber-50 border border-amber-200 rounded-input px-4 py-3">
              <AlertCircle size={16} className="text-amber-500 shrink-0" />
              <p className="text-xs text-amber-700">
                {ru ? 'Запись не найдена в базе данных. Вы всё равно можете продолжить.' : 'Ma\'lumotlar bazasida topilmadi. Davom etishingiz mumkin.'}
              </p>
            </div>
          )}

          {clientInfo && infoRows.length > 0 && (
            <div className="bg-blue-50 border border-blue-100 rounded-[16px] p-4 space-y-2.5">
              <p className="text-xs font-bold text-accent uppercase tracking-wide mb-3">
                {ru ? '✓ Данные найдены' : '✓ Ma\'lumot topildi'}
              </p>
              {infoRows.map(r => (
                <div key={r.label} className="flex items-start gap-2.5">
                  <span className="mt-0.5 shrink-0">{r.icon}</span>
                  <div>
                    <span className="text-xs text-muted">{r.label}: </span>
                    <span className="text-sm font-semibold text-gray-900">{r.val}</span>
                  </div>
                </div>
              ))}
              {(clientInfo.turnover_all || clientInfo.turnover_debit || clientInfo.accountant) && (
                <div className="mt-2 pt-2 border-t border-blue-200 space-y-1.5">
                  {clientInfo.accountant && (
                    <div className="flex justify-between gap-2">
                      <span className="text-xs text-muted">{ru ? 'Бош бухгалтер' : 'Bosh buxgalter'}:</span>
                      <span className="text-xs font-semibold text-gray-900 text-right">{clientInfo.accountant}</span>
                    </div>
                  )}
                  {clientInfo.turnover_all && (
                    <div className="flex justify-between gap-2">
                      <span className="text-xs text-muted">{ru ? 'Оборот (итого)' : 'Aylanma (jami)'}:</span>
                      <span className="text-xs font-semibold text-gray-900">{clientInfo.turnover_all}</span>
                    </div>
                  )}
                  {clientInfo.turnover_debit && (
                    <div className="flex justify-between gap-2">
                      <span className="text-xs text-muted">{ru ? 'Дебет' : 'Debet'}:</span>
                      <span className="text-xs font-semibold text-gray-900">{clientInfo.turnover_debit}</span>
                    </div>
                  )}
                  {clientInfo.turnover_credit && (
                    <div className="flex justify-between gap-2">
                      <span className="text-xs text-muted">{ru ? 'Кредит' : 'Kredit'}:</span>
                      <span className="text-xs font-semibold text-gray-900">{clientInfo.turnover_credit}</span>
                    </div>
                  )}
                </div>
              )}
            </div>
          )}
        </div>
      </Card>

      {/* Sphere count selector */}
      <Card padding="md">
        <p className="text-sm font-semibold text-gray-700 mb-3">
          {ru ? 'Количество сфер деятельности' : 'Faoliyat sohalari soni'}
        </p>
        <div className="flex flex-wrap gap-2">
          {[1, 2, 3, 4, 5].map(n => (
            <button
              key={n}
              onClick={() => setSphereCount(n)}
              className={`w-11 h-11 rounded-xl text-sm font-bold border-2 transition-all ${
                sphereCount === n
                  ? 'bg-accent text-white border-accent shadow-md'
                  : 'bg-white text-gray-600 border-border hover:border-accent hover:text-accent'
              }`}
            >
              {n}
            </button>
          ))}
        </div>
        <p className="text-xs text-muted mt-2">
          {ru ? `Выбрано: ${sphereCount} ${sphereCount === 1 ? 'сфера' : sphereCount < 5 ? 'сферы' : 'сфер'}` : `Tanlandi: ${sphereCount} soha`}
        </p>
      </Card>

      {!searched && (
        <p className="text-xs text-center text-muted">
          {ru ? 'Введите ПИНФЛ / ИНН и нажмите «Поиск» перед продолжением' : 'PINFL / INN kiriting va «Qidirish» tugmasini bosing'}
        </p>
      )}
      <Button variant="primary" fullWidth size="lg" onClick={handleNext} disabled={!searched}>
        {t(lang, 'next')}
      </Button>
    </div>
  )
}

// frontend/src/components/smeProfile/StepPinfl.vue
<script setup>
import { ref, computed } from 'vue'
import { useI18n } from 'vue-i18n'
import AppIcon from '@/components/AppIcon.vue'
import { smeProfileApi } from '@/services/smeProfileApi'

const props = defineProps({
  initialValue: { type: String, default: '' },
  initialClientInfo: { type: Object, default: null },
  initialSphereCount: { type: Number, default: 1 },
})
const emit = defineEmits(['next'])

const { t } = useI18n()

const value = ref(props.initialValue)
const error = ref('')
const searching = ref(false)
const clientInfo = ref(props.initialClientInfo)
const notFound = ref(false)
const sphereCount = ref(props.initialSphereCount)
const searched = ref(!!props.initialClientInfo)

async function handleSearch() {
  if (!value.value.trim()) {
    error.value = t('smeProfile.errors.empty')
    return
  }
  searching.value = true
  error.value = ''
  notFound.value = false
  clientInfo.value = null
  searched.value = false

  const res = await smeProfileApi.lookup(value.value.trim())
  searching.value = false
  searched.value = true

  if (!res.ok) {
    error.value = t('smeProfile.errors.backend')
    return
  }
  if (res.data.found) {
    clientInfo.value = {
      company_name:       res.data.company_name || '',
      director:           res.data.director || '',
      reg_address:        res.data.reg_address || '',
      phone:              res.data.phone || '',
      turnover_debit:     res.data.turnover_debit || '',
      turnover_credit:    res.data.turnover_credit || '',
      turnover_all:       res.data.turnover_all || '',
      shareholders_count: res.data.shareholders_count || '',
      accountant:         res.data.accountant || '',
      activity_type:      res.data.activity_type || '',
      sal_sum:            res.data.sal_sum || '',
    }
  } else {
    notFound.value = true
  }
}

function handleNext() {
  if (!value.value.trim()) {
    error.value = t('smeProfile.errors.empty')
    return
  }
  emit('next', {
    pinflInn: value.value.trim(),
    clientInfo: clientInfo.value,
    sphereCount: sphereCount.value,
  })
}

const infoRows = computed(() => {
  const ci = clientInfo.value
  if (!ci) return []
  return [
    { icon: 'business', label: t('smeProfile.fields.company'), val: ci.company_name },
    { icon: 'person',   label: t('smeProfile.fields.director'), val: ci.director },
    { icon: 'place',    label: t('smeProfile.fields.address'),  val: ci.reg_address },
    { icon: 'call',     label: t('smeProfile.fields.phone'),    val: ci.phone },
  ].filter((r) => r.val)
})
</script>

<template>
  <div class="space-y-6">
    <div class="text-center space-y-3">
      <div class="inline-flex items-center justify-center w-16 h-16 bg-primary/10 rounded-2xl">
        <AppIcon name="badge" class="text-primary text-3xl" filled />
      </div>
      <div>
        <h2 class="text-2xl font-bold text-on-surface">{{ t('smeProfile.pinfl.title') }}</h2>
        <p class="text-sm text-on-surface-variant mt-1">{{ t('smeProfile.pinfl.hint') }}</p>
      </div>
    </div>

    <div class="bg-surface-container-lowest rounded-xl p-6 shadow-sm">
      <label class="block text-sm font-semibold text-on-surface mb-3">
        {{ t('smeProfile.pinfl.label') }}
      </label>

      <div class="flex gap-2">
        <input
          v-model="value"
          type="text"
          :placeholder="t('smeProfile.pinfl.placeholder')"
          class="flex-1 sp-input"
          :class="{ 'sp-input--err': error }"
          @input="error = ''; clientInfo = null; notFound = false"
          @keydown.enter="handleSearch"
        />
        <button
          class="sp-btn sp-btn--primary"
          :disabled="searching || !value.trim()"
          @click="handleSearch"
        >
          <span
            v-if="searching"
            class="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin"
          />
          <AppIcon v-else name="search" />
          {{ t('smeProfile.pinfl.searchBtn') }}
        </button>
      </div>

      <p v-if="error" class="text-xs text-error font-medium mt-2">{{ error }}</p>

      <div
        v-if="notFound && !clientInfo"
        class="mt-4 flex items-center gap-2 bg-amber-50 border border-amber-200 rounded-lg px-4 py-3"
      >
        <AppIcon name="info" class="text-amber-600 text-base shrink-0" />
        <p class="text-xs text-amber-800">{{ t('smeProfile.pinfl.notFound') }}</p>
      </div>

      <div
        v-if="clientInfo && infoRows.length"
        class="mt-4 bg-primary/5 border border-primary/20 rounded-xl p-4 space-y-2.5"
      >
        <p class="text-xs font-bold text-primary uppercase tracking-wide mb-3">
          ✓ {{ t('smeProfile.pinfl.found') }}
        </p>
        <div v-for="r in infoRows" :key="r.label" class="flex items-start gap-2.5">
          <AppIcon :name="r.icon" class="text-primary text-base mt-0.5 shrink-0" />
          <div>
            <span class="text-xs text-on-surface-variant">{{ r.label }}: </span>
            <span class="text-sm font-semibold text-on-surface">{{ r.val }}</span>
          </div>
        </div>
        <div
          v-if="clientInfo.turnover_all || clientInfo.turnover_debit || clientInfo.accountant"
          class="mt-2 pt-2 border-t border-primary/20 space-y-1.5"
        >
          <div v-if="clientInfo.accountant" class="flex justify-between gap-2">
            <span class="text-xs text-on-surface-variant">{{ t('smeProfile.fields.accountant') }}:</span>
            <span class="text-xs font-semibold text-on-surface text-right">{{ clientInfo.accountant }}</span>
          </div>
          <div v-if="clientInfo.turnover_all" class="flex justify-between gap-2">
            <span class="text-xs text-on-surface-variant">{{ t('smeProfile.fields.turnoverAll') }}:</span>
            <span class="text-xs font-semibold text-on-surface">{{ clientInfo.turnover_all }}</span>
          </div>
          <div v-if="clientInfo.turnover_debit" class="flex justify-between gap-2">
            <span class="text-xs text-on-surface-variant">{{ t('smeProfile.fields.debit') }}:</span>
            <span class="text-xs font-semibold text-on-surface">{{ clientInfo.turnover_debit }}</span>
          </div>
          <div v-if="clientInfo.turnover_credit" class="flex justify-between gap-2">
            <span class="text-xs text-on-surface-variant">{{ t('smeProfile.fields.credit') }}:</span>
            <span class="text-xs font-semibold text-on-surface">{{ clientInfo.turnover_credit }}</span>
          </div>
        </div>
      </div>
    </div>

    <!-- Sphere count -->
    <div class="bg-surface-container-lowest rounded-xl p-5 shadow-sm">
      <p class="text-sm font-semibold text-on-surface mb-3">
        {{ t('smeProfile.pinfl.sphereCount') }}
      </p>
      <div class="flex flex-wrap gap-2">
        <button
          v-for="n in [1, 2, 3, 4, 5]"
          :key="n"
          class="w-11 h-11 rounded-xl text-sm font-bold border-2 transition-all"
          :class="
            sphereCount === n
              ? 'bg-primary text-white border-primary shadow-md'
              : 'bg-white text-on-surface-variant border-outline-variant hover:border-primary hover:text-primary'
          "
          @click="sphereCount = n"
        >
          {{ n }}
        </button>
      </div>
    </div>

    <button
      class="sp-btn sp-btn--primary w-full sp-btn--lg"
      :disabled="!value.trim()"
      @click="handleNext"
    >
      {{ t('smeProfile.next') }}
    </button>
  </div>
</template>

<style scoped>
.sp-input {
  padding: 0.875rem 1rem;
  border: 1px solid rgb(var(--md-sys-color-outline-variant) / 1);
  border-radius: 0.625rem;
  font-size: 0.875rem;
  outline: none;
  transition: border-color 0.15s, box-shadow 0.15s;
  background: white;
}
.sp-input:focus {
  border-color: rgb(var(--md-sys-color-primary) / 1);
  box-shadow: 0 0 0 3px rgb(var(--md-sys-color-primary) / 0.18);
}
.sp-input--err {
  border-color: rgb(var(--md-sys-color-error) / 1);
  background: rgb(254 242 242 / 1);
}
.sp-btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 0.5rem;
  padding: 0.875rem 1.25rem;
  border-radius: 0.625rem;
  font-size: 0.875rem;
  font-weight: 600;
  transition: all 0.15s;
  border: none;
  cursor: pointer;
}
.sp-btn--primary {
  background: rgb(var(--md-sys-color-primary) / 1);
  color: white;
}
.sp-btn--primary:hover:not(:disabled) {
  filter: brightness(1.05);
}
.sp-btn--primary:active:not(:disabled) {
  transform: scale(0.97);
}
.sp-btn--lg {
  padding: 1rem 1.5rem;
  font-size: 1rem;
}
.sp-btn:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}
</style>
