// frontend/src/components/smeProfile/StepQuestions.vue
<script setup>
import { ref, computed } from 'vue'
import { useI18n } from 'vue-i18n'
import AppIcon from '@/components/AppIcon.vue'
import AddressCascade from './AddressCascade.vue'

const props = defineProps({
  category: { type: Object, required: true },
  sphereIdx: { type: Number, required: true },
  sphereCount: { type: Number, required: true },
  initialAnswers: { type: Array, default: () => [] },
})
const emit = defineEmits(['next', 'back'])

const { t, locale } = useI18n()

const initMap = {}
props.initialAnswers.forEach((a) => {
  initMap[a.question_id] = a.answer
})
const answers = ref({ ...initMap })

function setAnswer(id, val) {
  answers.value = { ...answers.value, [id]: val }
}

function isChecked(qid, opt) {
  return (answers.value[qid] || '').split(',').filter(Boolean).includes(opt)
}
function toggleCheckbox(qid, opt) {
  const current = (answers.value[qid] || '').split(',').filter(Boolean)
  const next = current.includes(opt) ? current.filter((v) => v !== opt) : [...current, opt]
  setAnswer(qid, next.join(','))
}

const relatedCount = computed(() =>
  Math.max(0, Math.min(20, parseInt(answers.value['related_companies_count'] || '0', 10) || 0)),
)

function handleNext() {
  const baseAnswers = props.category.questions.map((q) => ({
    question_id: q.id,
    question_text_ru: q.text.ru,
    question_text_uz: q.text.uz,
    answer: answers.value[q.id] || '',
  }))
  const dyn = []
  for (let i = 0; i < relatedCount.value; i++) {
    const key = `related_company_inn_${i}`
    dyn.push({
      question_id: key,
      question_text_ru: `Связанная компания ${i + 1} — ИНН`,
      question_text_uz: `Bog'liq kompaniya ${i + 1} — INN`,
      answer: answers.value[key] || '',
    })
  }
  emit('next', { answers: [...baseAnswers, ...dyn] })
}

const isLast = computed(() => props.sphereIdx === props.sphereCount - 1)
</script>

<template>
  <div class="space-y-6">
    <div class="text-center space-y-2">
      <div class="inline-flex items-center justify-center w-14 h-14 bg-primary/10 rounded-2xl">
        <AppIcon name="quiz" class="text-primary text-2xl" />
      </div>
      <h2 class="text-2xl font-bold text-on-surface">{{ t('smeProfile.questions.title') }}</h2>
      <p class="text-sm text-on-surface-variant">
        {{
          t('smeProfile.questions.subtitle', {
            n: sphereIdx + 1,
            total: sphereCount,
            category: locale === 'ru' ? category.name.ru : category.name.uz,
          })
        }}
      </p>
    </div>

    <div class="bg-surface-container-lowest rounded-xl p-6 shadow-sm space-y-7">
      <div v-for="(q, idx) in category.questions" :key="q.id" class="space-y-2">
        <label class="block text-sm font-semibold text-on-surface">
          <span class="text-primary mr-1.5">{{ idx + 1 }}.</span>
          {{ locale === 'ru' ? q.text.ru : q.text.uz }}
        </label>

        <input
          v-if="q.type === 'text'"
          type="text"
          :value="answers[q.id] || ''"
          @input="setAnswer(q.id, $event.target.value)"
          class="sp-input"
        />

        <input
          v-else-if="q.type === 'number'"
          type="number"
          min="0"
          :value="answers[q.id] || ''"
          @input="setAnswer(q.id, $event.target.value)"
          class="sp-input"
        />

        <textarea
          v-else-if="q.type === 'textarea'"
          rows="3"
          :value="answers[q.id] || ''"
          @input="setAnswer(q.id, $event.target.value)"
          class="sp-input resize-y"
        />

        <select
          v-else-if="q.type === 'select'"
          :value="answers[q.id] || ''"
          @change="setAnswer(q.id, $event.target.value)"
          class="sp-input bg-white cursor-pointer"
        >
          <option value="">{{ t('smeProfile.selectPlaceholder') }}</option>
          <option v-for="o in (locale === 'ru' ? q.options.ru : q.options.uz)" :key="o" :value="o">
            {{ o }}
          </option>
        </select>

        <div v-else-if="q.type === 'radio'" class="space-y-1 pt-1">
          <label
            v-for="o in (locale === 'ru' ? q.options.ru : q.options.uz)"
            :key="o"
            class="flex items-center gap-3 cursor-pointer p-2 rounded-lg hover:bg-primary/5"
          >
            <input
              type="radio"
              :name="`${q.id}_s${sphereIdx}`"
              :value="o"
              :checked="answers[q.id] === o"
              @change="setAnswer(q.id, o)"
              class="w-4 h-4 accent-primary"
            />
            <span class="text-sm text-on-surface">{{ o }}</span>
          </label>
        </div>

        <div v-else-if="q.type === 'checkbox'" class="space-y-1 pt-1">
          <label
            v-for="o in (locale === 'ru' ? q.options.ru : q.options.uz)"
            :key="o"
            class="flex items-center gap-3 cursor-pointer p-2 rounded-lg hover:bg-primary/5"
          >
            <input
              type="checkbox"
              :checked="isChecked(q.id, o)"
              @change="toggleCheckbox(q.id, o)"
              class="w-4 h-4 accent-primary rounded"
            />
            <span class="text-sm text-on-surface">{{ o }}</span>
          </label>
        </div>

        <AddressCascade
          v-else-if="q.type === 'address_cascade'"
          :model-value="answers[q.id] || ''"
          @update:model-value="setAnswer(q.id, $event)"
        />

        <!-- Dynamic INN inputs after related_companies_count -->
        <div v-if="q.id === 'related_companies_count' && relatedCount > 0" class="mt-3 space-y-2 pl-1">
          <div v-for="i in relatedCount" :key="i">
            <label class="block text-xs font-semibold text-on-surface-variant mb-1">
              {{ t('smeProfile.questions.relatedCompany', { n: i }) }}
            </label>
            <input
              type="text"
              :value="answers[`related_company_inn_${i - 1}`] || ''"
              @input="setAnswer(`related_company_inn_${i - 1}`, $event.target.value)"
              class="sp-input"
              :placeholder="t('smeProfile.questions.relatedCompanyPlaceholder', { n: i })"
            />
          </div>
        </div>
      </div>
    </div>

    <div class="flex gap-3">
      <button class="sp-btn sp-btn--secondary flex-1" @click="emit('back')">
        {{ t('smeProfile.back') }}
      </button>
      <button class="sp-btn sp-btn--primary flex-1" @click="handleNext">
        {{ isLast ? t('smeProfile.summary.title') : t('smeProfile.next') }}
      </button>
    </div>
  </div>
</template>

<style scoped>
.sp-input {
  width: 100%;
  padding: 0.75rem 1rem;
  border: 1px solid rgb(var(--md-sys-color-outline-variant) / 1);
  border-radius: 0.625rem;
  font-size: 0.875rem;
  outline: none;
  transition: border-color 0.15s, box-shadow 0.15s;
  background: white;
}
.sp-input:focus {
  border-color: rgb(var(--md-sys-color-primary) / 1);
  box-shadow: 0 0 0 3px rgb(var(--md-sys-color-primary) / 0.18);
}
.sp-btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 0.5rem;
  padding: 0.875rem 1.25rem;
  border-radius: 0.625rem;
  font-size: 0.875rem;
  font-weight: 600;
  transition: all 0.15s;
  border: none;
  cursor: pointer;
}
.sp-btn--primary {
  background: rgb(var(--md-sys-color-primary) / 1);
  color: white;
}
.sp-btn--primary:hover {
  filter: brightness(1.05);
}
.sp-btn--secondary {
  background: rgb(var(--md-sys-color-surface-container) / 1);
  color: rgb(var(--md-sys-color-on-surface) / 1);
  border: 1px solid rgb(var(--md-sys-color-outline-variant) / 1);
}
.sp-btn--secondary:hover {
  background: rgb(var(--md-sys-color-surface-container-high) / 1);
}
</style>

// sme_oprosnyk/frontend/src/steps/StepQuestions.tsx
import { useState } from 'react'
import { ClipboardList } from 'lucide-react'
import { Lang, Category, AnswerItem } from '../types'
import { t } from '../i18n'
import Card from '../components/Card'
import Button from '../components/Button'
import AddressCascade from '../components/AddressCascade'

interface Props {
  lang: Lang
  category: Category
  sphereIdx: number
  sphereCount: number
  initialAnswers: AnswerItem[]
  onNext: (answers: AnswerItem[]) => void
  onBack: () => void
}

export default function StepQuestions({
  lang, category, sphereIdx, sphereCount, initialAnswers, onNext, onBack
}: Props) {
  const initMap: Record<string, string> = {}
  initialAnswers.forEach(a => { initMap[a.question_id] = a.answer })

  const [answers, setAnswers] = useState<Record<string, string>>(initMap)

  const setAnswer = (id: string, val: string) => setAnswers(p => ({ ...p, [id]: val }))

  const toggleCheckbox = (id: string, opt: string) => {
    const current = (answers[id] ?? '').split(',').filter(Boolean)
    const next = current.includes(opt) ? current.filter(v => v !== opt) : [...current, opt]
    setAnswer(id, next.join(','))
  }

  const handleNext = () => {
    const baseAnswers: AnswerItem[] = category.questions.map(q => ({
      question_id: q.id,
      question_text_ru: q.text.ru,
      question_text_uz: q.text.uz,
      answer: answers[q.id] ?? '',
    }))

    // Append dynamic related company INN answers if count > 0
    const count = parseInt(answers['related_companies_count'] ?? '0', 10) || 0
    const dynamicAnswers: AnswerItem[] = []
    for (let i = 0; i < count; i++) {
      const key = `related_company_inn_${i}`
      const val = answers[key] ?? ''
      dynamicAnswers.push({
        question_id: key,
        question_text_ru: `Связанная компания ${i + 1} — ИНН`,
        question_text_uz: `Bog'liq kompaniya ${i + 1} — INN`,
        answer: val,
      })
    }

    onNext([...baseAnswers, ...dynamicAnswers])
  }

  const subtitle = t(lang, 'questions_sphere')
    .replace('{n}', String(sphereIdx + 1))
    .replace('{total}', String(sphereCount))
    .replace('{category}', category.name[lang])

  const isLast = sphereIdx === sphereCount - 1
  const ru = lang === 'ru'

  const inputCls = 'w-full px-4 py-3 border border-border rounded-input text-sm focus:outline-none focus:ring-2 focus:ring-accent/30 focus:border-accent transition-colors'
  const optionCls = 'flex items-center gap-3 cursor-pointer group p-2 rounded-lg hover:bg-blue-50 transition-colors'

  // How many related company INN fields to show
  const relatedCount = Math.max(0, Math.min(20, parseInt(answers['related_companies_count'] ?? '0', 10) || 0))

  return (
    <div className="space-y-6">
      <div className="text-center space-y-2">
        <div className="inline-flex items-center justify-center w-14 h-14 bg-blue-50 rounded-2xl">
          <ClipboardList size={28} className="text-accent" />
        </div>
        <h2 className="text-2xl font-bold text-primary">{t(lang, 'questions_title')}</h2>
        <p className="text-sm text-muted">{subtitle}</p>
      </div>

      <Card>
        <div className="space-y-7">
          {category.questions.map((q, idx) => {
            const text = q.text[lang]
            const opts = q.options[lang]
            const val  = answers[q.id] ?? ''

            return (
              <div key={q.id} className="space-y-2">
                <label className="block text-sm font-semibold text-gray-800">
                  <span className="text-accent mr-1.5">{idx + 1}.</span>
                  {text}
                </label>

                {q.type === 'text' && (
                  <input type="text" value={val} onChange={e => setAnswer(q.id, e.target.value)}
                    placeholder={text} className={inputCls} />
                )}

                {q.type === 'number' && (
                  <input type="number" value={val} min={0}
                    onChange={e => setAnswer(q.id, e.target.value)} className={inputCls} />
                )}

                {q.type === 'textarea' && (
                  <textarea value={val} rows={3} placeholder={text}
                    onChange={e => setAnswer(q.id, e.target.value)}
                    className={inputCls + ' resize-y'} />
                )}

                {q.type === 'select' && (
                  <select value={val} onChange={e => setAnswer(q.id, e.target.value)}
                    className={inputCls + ' bg-white appearance-none cursor-pointer'}>
                    <option value="">{t(lang, 'select_placeholder')}</option>
                    {opts.map(o => <option key={o} value={o}>{o}</option>)}
                  </select>
                )}

                {q.type === 'radio' && (
                  <div className="space-y-1 pt-1">
                    {opts.map(o => (
                      <label key={o} className={optionCls}>
                        <input type="radio" name={`${q.id}_s${sphereIdx}`} value={o}
                          checked={val === o} onChange={() => setAnswer(q.id, o)}
                          className="w-4 h-4 accent-accent" />
                        <span className="text-sm text-gray-700 group-hover:text-gray-900">{o}</span>
                      </label>
                    ))}
                  </div>
                )}

                {q.type === 'checkbox' && (
                  <div className="space-y-1 pt-1">
                    {opts.map(o => {
                      const checked = (val ?? '').split(',').filter(Boolean).includes(o)
                      return (
                        <label key={o} className={optionCls}>
                          <input type="checkbox" checked={checked}
                            onChange={() => toggleCheckbox(q.id, o)}
                            className="w-4 h-4 accent-accent rounded" />
                          <span className="text-sm text-gray-700 group-hover:text-gray-900">{o}</span>
                        </label>
                      )
                    })}
                  </div>
                )}

                {q.type === 'address_cascade' && (
                  <AddressCascade lang={lang} value={val} onChange={v => setAnswer(q.id, v)} />
                )}

                {/* Dynamic INN fields after related_companies_count */}
                {q.id === 'related_companies_count' && relatedCount > 0 && (
                  <div className="mt-3 space-y-2 pl-1">
                    {Array.from({ length: relatedCount }, (_, i) => (
                      <div key={i}>
                        <label className="block text-xs font-semibold text-muted mb-1">
                          {ru ? `Компания ${i + 1} — ИНН` : `Kompaniya ${i + 1} — INN`}
                        </label>
                        <input
                          type="text"
                          value={answers[`related_company_inn_${i}`] ?? ''}
                          onChange={e => setAnswer(`related_company_inn_${i}`, e.target.value)}
                          placeholder={ru ? `ИНН компании ${i + 1}` : `Kompaniya ${i + 1} INN`}
                          className={inputCls}
                        />
                      </div>
                    ))}
                  </div>
                )}
              </div>
            )
          })}
        </div>
      </Card>

      <div className="flex gap-3">
        <Button variant="secondary" onClick={onBack} className="flex-1">
          {t(lang, 'back')}
        </Button>
        <Button variant="primary" onClick={handleNext} className="flex-1">
          {isLast ? t(lang, 'step_summary') : t(lang, 'next')}
        </Button>
      </div>
    </div>
  )
}
